name: Build thyme Kernel with KSU

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        fetch-depth: 1  # 相当于 git clone --depth=1，加快速度

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git curl wget bison flex zip bc cpio libssl-dev ccache python-is-python3 unzip

    - name: Setup proton-clang toolchain
      run: |
        mkdir -p $HOME/proton-clang
        cd $HOME/proton-clang
        wget https://github.com/kdrag0n/proton-clang/archive/refs/tags/20210522.zip
        unzip 20210522.zip
        cd $GITHUB_WORKSPACE

    - name: Build kernel for thyme with KSU
      run: |
        bash build.sh thyme ksu

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lmi-ksu-kernel
        path: |
          *.zip
          out/arch/arm64/boot/Image
          out/arch/arm64/boot/dtb
